export const en = {
  login: {
    title: 'Sign In',
    emailPlaceholder: 'Email',
    passwordPlaceholder: 'Password',
    loginButton: 'Login',
    signupPrompt: "Don't have an account?",
    signupLink: 'Sign Up',
    emailRequired: 'Please enter your email',
    passwordRequired: 'Please enter your password',
    bothRequired: 'Please enter both email and password',
    invalidEmail: 'Invalid email address',
    userNotFound: 'No user found with this email',
    wrongPassword: 'Incorrect password',
    loginFailed: 'Login failed. Please try again.',
    goToSignup: 'Go to signup',
    loginScreenTitle: 'Login screen title',
  },
  signup: {
    title: 'Sign Up',
    emailPlaceholder: 'Email',
    passwordPlaceholder: 'Password',
    confirmPasswordPlaceholder: 'Confirm Password',
    signupButton: 'Sign Up',
    loginPrompt: 'Already have an account?',
    loginLink: 'Login',
    emailRequired: 'Email is required',
    passwordRequired: 'Password is required',
    passwordsDoNotMatch: 'Passwords do not match',
    invalidEmail: 'Invalid email format',
    passwordTooShort: 'Password must be at least 6 characters',
    emailAlreadyInUse: 'Email is already registered',
    weakPassword: 'Password is too weak',
    signupFailed: 'Signup failed. Please try again.',
    accountCreated: 'Account created successfully',
  },
  profile: {
    screenTitle: 'Profile',
    avatar: 'User avatar',
    defaultName: 'User Profile',
    noEmail: 'No email',
    emailVerified: 'Email Verified',
    yes: 'Yes',
    no: 'No',
    name: 'Name',
    phoneNumber: 'Phone Number',
    dateOfBirth: 'Date of Birth',
    address: 'Address',
    logout: 'Logout',
  }
};
